apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z4bw6m8t3-nodejs
  janus-idp.io/tekton: z4bw6m8t3-nodejs
  backstage.io/kubernetes-id: z4bw6m8t3-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: z4bw6m8t3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
